### ISSUE TITLE
cellType cov weighted loss function is ambiguous

### ISSUE THREAD

**Issue by GitHUB-ZYD** [beyondpie/CEMBA_wmb_snATAC#18]
![image](https://github.com/user-attachments/assets/bfb9f215-00af-49f1-9ea8-fcbc741477bc)
hello.
i am ambiguous while read the paper with the loss function. And no code in directory 11.deeplearning.

What data was used to calculate the covariance matrix between different cell types? The y_true which used to calculate the loss  ? the y_true of each epoch? Or y_true of the entire dataset ? shold diagonal elements need to be removed to calculate the mean of CoV for each cell type?

**Comment by beyondpie** [comment]
@GitHUB-ZYD 
Hi there, sorry for the late response. 
Please check the deep learning codes here: https://github.com/yal054/mba_dl_model. I will later upload the deep learning codes in this repo.
